#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'runit'

cookbook 'apt', 
  :git => 'git://github.com/opscode-cookbooks/apt.git'

cookbook 'build-essential', 
  :git => 'git://github.com/opscode-cookbooks/build-essential.git'

cookbook 'git', 
  :git => 'git://github.com/opscode-cookbooks/git.git'

cookbook 'postgresql', 
  :git => 'git://github.com/opscode-cookbooks/postgresql.git'

cookbook 'nginx', 
  :git => 'git://github.com/opscode-cookbooks/nginx.git'

cookbook 'java', 
  :git => 'git://github.com/opscode-cookbooks/java.git'

cookbook 'jetty', 
  :git => 'git://github.com/opscode-cookbooks/jetty.git'

cookbook 'facemidia', 
  :git => 'git://github.com/lopesivan/cook-facemidia.git'

#cookbook 'hello_world', 
#  :git => 'git://github.com/lopesivan/cook-hello_world.git',
#  :ref => "tags/0.1.0"
